import Vue from 'vue'
import { Divider, Row, Col, Calendar, Card, Carousel, CarouselItem, Steps, Step, Tabs, TabPane, Aside, Progress, Rate, Button, Dropdown, DropdownItem, DropdownMenu, Container, Header, Main, MenuItem, Menu, Submenu, Select, Option, Form, FormItem, Input, Message, RadioGroup, Radio, MessageBox, Collapse, CollapseItem, Tag, Table, TableColumn } from 'element-ui'

Vue.use(Divider)
Vue.use(Col)
Vue.use(Row)
Vue.use(Button)
Vue.use(Form)
Vue.use(Card)
Vue.use(FormItem)
Vue.use(Input)
Vue.use(Radio)
Vue.use(RadioGroup)
Vue.use(Collapse)
Vue.use(CollapseItem)
Vue.use(Select)
Vue.use(Option)
Vue.use(Tag)
Vue.use(Tabs)
Vue.use(TabPane)
Vue.use(Table)
Vue.use(TableColumn)
Vue.use(Aside)
Vue.use(Container)
Vue.use(Header)
Vue.use(Progress)
Vue.use(Main)
Vue.use(Submenu)
Vue.use(Dropdown)
Vue.use(DropdownItem)
Vue.use(DropdownMenu)
Vue.use(Menu)
Vue.use(MenuItem)
Vue.use(Rate)
Vue.use(Carousel)
Vue.use(Step)
Vue.use(Steps)
Vue.use(Calendar)
Vue.use(CarouselItem)
Vue.prototype.$message = Message
Vue.prototype.$alert = MessageBox.alert
Vue.prototype.$confirm = MessageBox.confirm
